apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ycxix5d7l-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ycxix5d7l-go 
  name: ycxix5d7l-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ycxix5d7l-go 
